import Image from 'next/image'
import Head from 'next/head'
import deved from '../../public/kamal.jpg'
import design from '../../public/design.png'
import code from '../../public/code.png'
import web1 from '../../public/web1.png'
import mini from '../../public/mini.png'
import dept from '../../public/dept.png'
import yt from '../../public/yt.png'
import best from '../../public/best.png'
import { AiFillMail, AiFillYoutube, AiFillLinkedin} from 'react-icons/ai';
export default function Home() {
  return (
      <div>
        <Head>
          <title>Rajkamal Portofolio</title>
          <meta name="description" content="Generated by cre" />
          <link rel="icon" href="/favicon.ico"/>
      
        </Head>

        <main className='bg-white px-10 md:px-20 lg:px-40'>
          <section className='min-h-screen'>
            <nav className='p-10 mb-12 flex justify-between'>
              <h1 className='text-xl text-black font-mono'>#developedbyed</h1>
              <ul className='flex items-center'>
                <li>

                </li>
                <li>
                  <a className='bg-cyan-600 text-white px-4 py-2 rounded-md ml-8' href='https://www.linkedin.com/in/rajkamal-srinivasan-591317290/'>linkedin</a>
                </li>
              </ul>
            </nav>

            <div className='text-center p-10 py-10 '>
              <h2 className='text-5xl py-2 text-pink-400 font-medium md:text-6xl'>Rajkamal S</h2>
              <h3 className='text-2xl py-2 text-gray-800'>Student and developer</h3>
              <p className='text-md py-5 text-gray-800 md:text-xl max-w-xl mx-auto'>
               Greetings! I'm an ambitious B.Tech Computer Science student, driven by a profound passion for technology. 
              </p>
              <p className='text-md py-1 text-gray-800 md:text-xl max-w-xl mx-auto'>
               With a solid foundation in programming, I'm geared up to make a significant impact in the tech industry. 
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-8 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/rajkamal-srinivasan-591317290/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://www.youtube.com/@MrSniteTamil/videos" target="_blank" rel="noopener noreferrer">
              <AiFillYoutube />
            </a>
            </div>
            <div className='relative mx-auto rounded-full w-80 h-80'>
                <Image
                  src={deved} className='rounded-full' />
                
            </div>
          </section>

          <section>
            <div className='p-5'>
              <h3 className='text-3xl py-1 text-black'>My Skills</h3>
              <p className='text-md py-2 text-gray-800'>
                I aspire to leverage my <span className='text-pink-400'>skills</span> to develop innovative solutions that drive my carrer to success in the tech landscape.
              </p>
              <p className='text-md py-2 text-gray-800'>
                As an content creator on <span className='text-pink-400'>YouTube</span>  platform I developed the skills that allows me work more efficient
              </p>
            </div>

            <div className='lg:flex gap-10'>
  {/* Creative Apps Section */}
                  <div className='text-center shadow-lg rounded-xl my-10 flex-1'>
                    <div className='relative'>
                      <Image src={design} width={100} height={100} className='mx-auto' />
                    </div>
                    <h3 className='text-pink-600 py-2'>Creative Apps</h3>
                    <ul className='text-gray-800 list-none  justify-center'>
                      <li>Adobe Premiere Pro</li>
                      <li>Adobe Photoshop</li>
                      <li>Unreal Engine</li>
                      <li>MS Office</li>
                    </ul>
                  </div>

                  {/* Programming Languages Section */}
                  <div className="text-center shadow-lg rounded-xl my-10 flex-1">
                    <div className="relative">
                      <Image src={code} width={100} height={100} className="mx-auto" />
                    </div>
                    <h3 className="py-4 text-teal-600">Programming Languages I Know</h3>
                    <ul className="text-gray-800 list-none justify-center">
                      <li>ReactJs</li>
                      <li>HTML & CSS</li>
                      <li>C/C++</li>
                      <li>Python</li>
                    </ul>
                  </div>
                </div>

          </section>
          <section>
          <div className='p-5'>
              <h3 className='text-3xl text-gray-800'>Portfolio</h3>
              <p className='text-2xl text-pink-600'>Projects and Research</p>
            </div>
            <div className='p-5 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              {/* Single landscape image */}
              <a href="https://dizuz-app-enhm-7btst3ca4-rajkamalcode.vercel.app/" target="_blank" rel="noopener noreferrer">
              <div className="basis-full flex-1 p-1">
                <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                <p className='text-gray-800 text-center'>A social media app like Twitter with MongoDB backend, created with community features</p>
              </div>
              </a>

              {/* Stacked vertical portrait images */}
              <div className="lg:flex lg:flex-row gap-10">
                <div className="basis-full lg:flex-none">
                  <Image src={dept} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                  <p className='text-gray-800 text-center'>Department project done to automate lighting system in college campus</p>
                </div>

                <div className="basis-full lg:flex-none">
                  <Image src={mini} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                  <p className='text-gray-800 text-center'>A research done on gaming technology and simulators </p>
                  <p className='text-gray-800 text-center'>to solve real life infrastructure </p>
                </div>
              </div>
            </div>
          <div>
            <div className='p-5'>
              <h3 className='text-3xl py-1 text-gray-800'>Achievements</h3>
              <p className='text-2xl text-pink-600'>YouTuber</p>
              <p className='text-black'>I'm the creator behind MrSnite Tamil which has over 48,000 Subscribers, focused on Computer Hardware and the Gaming Industry. 
                Despite prevalent misconceptions, I'm passionate about fostering growth in this niche within India. 
                This passion has helped me in many ways including improving my Communication skills, Video editing skills and particularly ethics and consistency.
                I've uploaded a video every day for 2 years. </p>
            </div>

            <div className='p-5 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            {/* Single landscape image */}
            <a href="https://www.youtube.com/@MrSniteTamil/videos" target="_blank" rel="noopener noreferrer">
              <div className="basis-full flex-1 p-1 cursor-pointer">
                <Image src={yt} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                <p className='text-gray-800 text-center'>My Youtube channel focuses on Tech and Gaming Industry</p>
              </div>
            </a>
          </div>
          <div className='p-5'>
              <p className='text-2xl text-pink-600'>Award for best paper</p>
              <p className='text-black'>In a group of 3, I attended National conference on technology for society (NCTS'23) on 19th october. I presented our research project on using simulation video game to test the viablity of Infrastructure and Government projects. </p>
            </div>
          <div className='p-5 flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            {/* Single landscape image */}
              <div className="basis-full flex-1 p-1 cursor-pointer">
                <Image src={best} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                <p className='text-gray-800 text-center'>Best paper award in NCTS conference</p>
              </div>
          </div>

          </div>
          </section>
        </main>
        <footer className="bg-gray-900 text-white p-5 flex flex-col items-center justify-center">
          <div className="mb-5 text-center">
            <h3 className="text-2xl font-bold">Connect with Me</h3>
            <h2>srajkamal717@gmail.com</h2>
            <div className="px-5 flex gap-5">
              <a href="mailto:srajkamal717@gmail.com">
                <AiFillMail className="text-4xl cursor-pointer" />
              </a>
              <a href="https://www.linkedin.com/in/rajkamal-srinivasan-591317290/" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin className="text-4xl cursor-pointer" />
              </a>
              <a href="https://www.youtube.com/@MrSniteTamil/videos" target="_blank" rel="noopener noreferrer">
                <AiFillYoutube className="text-4xl cursor-pointer" />
              </a>
            </div>
          </div>
          <div className="mt-5 text-center">
            <p>&copy; 2023 Rajkamal S. All rights reserved.</p>
          </div>
        </footer>
      </div>
  )
}
